theme: minima
title: Suraj In Cloud

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: surajincloud
    github:  surajincloud
    instagram: surajincloud
    linkedin: suraj.narwade
    youtube: surajincloud
    youtube_channel_name: SurajinCloud
